### ISSUE TITLE
morphosyntactic parser throws tmp xml-file not found

### ISSUE THREAD

**Issue by wmkouw** [ADAH-EviDENce/NewsReader#28]
Goal: run morphosyntactic_parser_nl (alpinonaf) on tokenized naf file.

Input: `cat file.naf | python -m alpinonaf -t 0.05 > out.naf`

Problem: After tokenizing, during parsing, alpinonaf throws an exception that it can't find a temporary file it created; 
```
WARNING] Not found the file ['/tmp/tmpXpNQAI/9.xml', '/tmp/tmpXpNQAI/305.xml', '/tmp/tmpXpNQAI/404.xml', '/tmp/tmpXpNQAI/888.xml', '/tmp/tmpXpNQAI/1386.xml']
```

Stack trace:
```
! Existence error in argument 1 of open/3
! file '/tmp/tmpXpNQAI/9.xml' does not exist
! goal:  open('/tmp/tmpXpNQAI/9.xml',read,_24)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/alpinonaf/__main__.py", line 25, in <module>
  File "build/bdist.linux-x86_64/egg/alpinonaf/morph_syn_parser.py", line 330, in parse
  File "build/bdist.linux-x86_64/egg/alpinonaf/morph_syn_parser.py", line 269, in call_alpino_local
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
```

**Comment by wmkouw** [comment]
Lines 260-262 check if any xml files are missing:
```
    missing_files = [xml_file for xml_file in xml_files if not os.path.exists(xml_file)]
    if missing_files:
        logging.warning('Not found the file {}'.format(missing_files))
```

But all files are still submitted to Alpino in line 267:
```
cmd = [alpino_bin, '-treebank_triples'] + xml_files
```

I've now changed it to including only the existing xml files:
```
    cmd = [alpino_bin, '-treebank_triples'] + [xml_file for xml_file in xml_files if os.path.exists(xml_file)]
```

**Comment by wmkouw** [comment]
`Alpino -treebank_triples` exceeds time budget drastically. 

In fact, the `check_output(cmd)` command hangs in Python, but `Alpino -treebank_triples` runs smoothly in Bash.

It seems that `check_output` has a volume limit on child processes: https://stackoverflow.com/questions/1180606/using-subprocess-popen-for-process-with-large-output

**Comment by wmkouw** [comment]
Fixed stdout/stderr hanging by setting stderr to None in a Pope process.

Replace (line 269 of morph_syn_parser.py):
```
output = check_output(cmd)
```

with
```
output = Popen(cmd, stdout=PIPE, stderr=None).stdout.read()
```

After this fix, you run into the incomplete xml_files list again (see 2 comments above). Fixed this by inserting a line after `logging.warning('Not found the file {}'.format(missing_files))` (line 262) containing a glob:
```
xml_files = glob(out_folder_alp + '*.xml')
```
(make sure to import glob as well; i.e. `from glob import glob` at top).

**Comment by wmkouw** [comment]
Glob wasn't working. New replacement:
```
xml_files = [xml_file for xml_file in xml_files if os.path.exists(xml_file)]
```
