### ISSUE TITLE
connections to dbpedia services time out

### ISSUE THREAD

**Issue by wmkouw** [ADAH-EviDENce/NewsReader#5]
Goal: run dbpedia_ner for named entity recognition 

Input: 
```
cat infile.naf | python2 dbpedia_ner.py
```

Problem: url connection request times out. Are the servers turned off?

```
Traceback (most recent call last):
  File "dbpedia_ner.py", line 163, in <module>
    dbpedia_xml_results = call_dbpedia_rest_service(whole_text,args.dbpedia_url,args.confidence)
  File "dbpedia_ner.py", line 38, in call_dbpedia_rest_service
    handler = urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by wmkouw** [comment]
Downloads for locally running dbpedia-spotlight:

```bash
wget http://downloads.dbpedia-spotlight.org/spotlight/dbpedia-spotlight-0.7.1.jar 
wget http://downloads.dbpedia-spotlight.org/2016-10/nl/model/nl.tar.gz
```

**Comment by wmkouw** [comment]
`http://spotlight.sztaki.hu/downloads/` times out as well.

**Comment by wmkouw** [comment]
Locally installing the jar and running the server is the only solution at the moment.
